name: "test"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build-and-check:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - uses: cachix/cachix-action@v14
        with:
          name: timhae-firefly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
      - run: nix flake check
